### ISSUE TITLE
交流学习

### ISSUE THREAD

**Issue by ForrestPi** [HarshWinterBytes/High_Fidelity_3DFaceRecon#1]
你是在复现ganFit 算法是吧 你有大量的人脸texture展开图吗？可以多多交流

**Comment by HarshWinterBytes** [comment]
我目前复现的是这一篇：Jongyoo Kim, Jiaolong Yang, Xin Tong; Proceedings of the IEEE/CVF International Conference on Computer Vision (ICCV), 2021, pp. 13990-13999
不知你说的ganFit是哪一篇
人脸展开图的话我目前正在做，但是自遮挡部分的结果一直不好

**Comment by ForrestPi** [comment]
GANFIT: Generative Adversarial Network Fitting for High Fidelity 3D Face Reconstruction 
 https://arxiv.org/abs/1902.05978
这篇作者有一套人脸texture展开图数据，不过没有开源
可以多多交流，我也做3D人脸重建

**Comment by HarshWinterBytes** [comment]
> GANFIT: Generative Adversarial Network Fitting for High Fidelity 3D Face Reconstruction https://arxiv.org/abs/1902.05978 这篇作者有一套人脸texture展开图数据，不过没有开源 可以多多交流，我也做3D人脸重建

嗯嗯
